---
stages:
  - test
  - prod

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

build-test-deploy-testnet:
  script:
    - yarn install
    - yarn build:testnet
    - rsync -e "ssh -o StrictHostKeyChecking=no" -avz build/ root@labs.wax.eosdetroit.io:/var/www/waxlabs-ui
  stage: test
  artifacts:
    paths:
      - build/
  rules:
    - if: '$CI_COMMIT_BRANCH == "testnet"'

build-test-deploy-mainnet:
  script:
    - yarn install
    - yarn build:prod
  stage: prod
  artifacts:
    paths:
      - build/
  rules:
    - if: '$CI_COMMIT_BRANCH != "testnet"'
