---
stages:
  - test
  - deploy
  - build

build-and-deploy-testnet:
  image:
    name: node:16-alpine
  script:
    - yarn install
    - yarn build:testnet
    - cd build && rsync -e "ssh -o StrictHostKeyChecking=no" -avz . root@142.93.203.27:/usr/share/nginx/html/waxlabs --delete
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "testnet"'

build-production:
  image:
    name: node:16-alpine
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG'
  allow_failure: false
  script:
    - yarn install
    - yarn build:prod
  artifacts:
    paths:
      - build/

validate-pr:
  image:
    name: node:16-alpine
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - yarn install
    - yarn lint --max-warnings=0
