---
default:
  image: node:14-alpine

stages:
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

build-and-deploy-testnet:
  script:
    - yarn install
    - yarn build:testnet
    - cd build && rsync -e "ssh -o StrictHostKeyChecking=no" -avz . root@142.93.203.27:/usr/share/nginx/html/waxlabs --delete
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "testnet"'
