---
stages:
  - test
  - deploy
  - build

build-and-deploy-testnet:
  script:
    - yarn install
    - yarn build --mode test
    - cd dist && rsync -e "ssh -o StrictHostKeyChecking=no" -avz . root@142.93.203.27:/usr/share/nginx/html/waxlabs-v3 --delete
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "testnet"'

validate-pr:
  image:
    name: node:18-alpine
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - yarn install
    - yarn tsc
    - yarn lint --max-warnings=0
