name: Mainnet build on tag
on:
  push:
    tags:
      - '**'  # Runs on any tag push to the main branch
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
